# Generated by Django 4.2.11 on 2025-11-07 16:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="influencer_avatars/"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(13),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("language", models.CharField(default="Arabic", max_length=100)),
                (
                    "primary_category",
                    models.CharField(
                        choices=[
                            ("fashion", "Fashion"),
                            ("beauty", "Beauty"),
                            ("fitness", "Fitness"),
                            ("food", "Food"),
                            ("travel", "Travel"),
                            ("tech", "Technology"),
                            ("gaming", "Gaming"),
                            ("lifestyle", "Lifestyle"),
                            ("business", "Business"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                            ("sports", "Sports"),
                            ("music", "Music"),
                            ("art", "Art"),
                            ("parenting", "Parenting"),
                            ("health", "Health"),
                            ("finance", "Finance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "secondary_categories",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Influencer",
                "verbose_name_plural": "Influencers",
                "db_table": "influencers_influencer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InfluencerTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "influencers_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InfluencerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audience_age_13_17", models.FloatField(default=0.0)),
                ("audience_age_18_24", models.FloatField(default=0.0)),
                ("audience_age_25_34", models.FloatField(default=0.0)),
                ("audience_age_35_44", models.FloatField(default=0.0)),
                ("audience_age_45_54", models.FloatField(default=0.0)),
                ("audience_age_55_plus", models.FloatField(default=0.0)),
                ("audience_gender_male", models.FloatField(default=0.0)),
                ("audience_gender_female", models.FloatField(default=0.0)),
                ("top_audience_countries", models.JSONField(blank=True, default=dict)),
                ("top_audience_cities", models.JSONField(blank=True, default=dict)),
                ("avg_engagement_rate", models.FloatField(default=0.0)),
                ("best_posting_times", models.JSONField(blank=True, default=list)),
                (
                    "most_engaging_content_types",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "estimated_rate_per_post",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("collaboration_count", models.PositiveIntegerField(default=0)),
                (
                    "authenticity_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "influence_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "influencer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="influencers.influencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Influencer Analytics",
                "verbose_name_plural": "Influencer Analytics",
                "db_table": "influencers_analytics",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("snapchat", "Snapchat"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("followers_count", models.PositiveIntegerField(default=0)),
                ("following_count", models.PositiveIntegerField(default=0)),
                ("posts_count", models.PositiveIntegerField(default=0)),
                (
                    "engagement_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("avg_likes", models.PositiveIntegerField(default=0)),
                ("avg_comments", models.PositiveIntegerField(default=0)),
                ("avg_shares", models.PositiveIntegerField(default=0)),
                ("avg_views", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="influencers.influencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Account",
                "verbose_name_plural": "Social Media Accounts",
                "db_table": "influencers_socialmediaaccount",
                "unique_together": {("influencer", "platform", "username")},
            },
        ),
        migrations.CreateModel(
            name="InfluencerTagging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="influencers.influencer",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencers",
                        to="influencers.influencertag",
                    ),
                ),
            ],
            options={
                "db_table": "influencers_tagging",
                "unique_together": {("influencer", "tag")},
            },
        ),
    ]
