# Generated by Django 4.2.11 on 2025-11-11 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("influencers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluencerDataImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("username_list", "Username List Import"),
                            ("social_blade", "Social Blade Data"),
                            ("manual_averages", "Manual Average Metrics"),
                            ("sponsored_content", "Sponsored Content"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source_file",
                    models.FileField(blank=True, null=True, upload_to="imports/"),
                ),
                (
                    "import_data",
                    models.JSONField(default=dict, help_text="Raw import data"),
                ),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("successful_records", models.PositiveIntegerField(default=0)),
                ("failed_records", models.PositiveIntegerField(default=0)),
                ("error_log", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Data Import",
                "verbose_name_plural": "Data Imports",
                "db_table": "influencers_dataimport",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SponsoredPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_url",
                    models.URLField(help_text="Direct link to the sponsored post"),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("carousel", "Carousel"),
                            ("reel", "Reel"),
                            ("story", "Story"),
                            ("igtv", "IGTV"),
                            ("youtube_video", "YouTube Video"),
                            ("tiktok_video", "TikTok Video"),
                            ("tweet", "Tweet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caption", models.TextField(blank=True, null=True)),
                ("hashtags", models.TextField(blank=True, null=True)),
                ("brand_name", models.CharField(max_length=200)),
                (
                    "brand_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("sponsored", "Sponsored Post"),
                            ("partnership", "Brand Partnership"),
                            ("gifted", "Gifted Product"),
                            ("collaboration", "Collaboration"),
                            ("ambassador", "Brand Ambassador"),
                            ("affiliate", "Affiliate Marketing"),
                        ],
                        default="sponsored",
                        max_length=50,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("saves_count", models.PositiveIntegerField(default=0)),
                (
                    "engagement_rate",
                    models.FloatField(
                        default=0.0, help_text="Post-specific engagement rate"
                    ),
                ),
                (
                    "disclosure_present",
                    models.BooleanField(
                        default=False, help_text="#ad, #sponsored, etc."
                    ),
                ),
                (
                    "disclosure_text",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("product_mentions", models.TextField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("estimated_reach", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per mille",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cpe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per engagement",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("manually_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("posted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sponsored Post",
                "verbose_name_plural": "Sponsored Posts",
                "db_table": "influencers_sponsoredpost",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.AddField(
            model_name="influencer",
            name="avg_comments",
            field=models.PositiveIntegerField(
                default=0, help_text="Average comments per post"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="avg_likes",
            field=models.PositiveIntegerField(
                default=0, help_text="Average likes per post"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="avg_saves",
            field=models.PositiveIntegerField(
                default=0, help_text="Average saves per post"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="avg_shares",
            field=models.PositiveIntegerField(
                default=0, help_text="Average shares per post"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="avg_views",
            field=models.PositiveIntegerField(
                default=0, help_text="Average views per post"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="country",
            field=models.CharField(
                default="Morocco", help_text="Primary country/market", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("social_blade", "Social Blade"),
                    ("scraping", "Web Scraping"),
                    ("api", "Platform API"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="followers_growth_14d",
            field=models.IntegerField(
                default=0, help_text="Followers gained in last 14 days"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="followers_growth_rate_14d",
            field=models.FloatField(
                default=0.0, help_text="Growth rate percentage in last 14 days"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="is_influencer",
            field=models.BooleanField(
                default=True, help_text="Manually verified as actual influencer"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="manual_data_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="influencer",
            name="posts_count_14d",
            field=models.PositiveIntegerField(
                default=0, help_text="Posts count in last 14 days"
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="social_blade_data_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialmediaaccount",
            name="avg_saves",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="socialmediaaccount",
            name="followers_14d_ago",
            field=models.PositiveIntegerField(
                default=0, help_text="Followers count 14 days ago"
            ),
        ),
        migrations.AddField(
            model_name="socialmediaaccount",
            name="followers_growth_14d",
            field=models.IntegerField(
                default=0, help_text="Followers gained in last 14 days"
            ),
        ),
        migrations.AddField(
            model_name="socialmediaaccount",
            name="followers_growth_rate_14d",
            field=models.FloatField(
                default=0.0, help_text="Growth rate % in last 14 days"
            ),
        ),
        migrations.AddField(
            model_name="socialmediaaccount",
            name="posts_count_14d",
            field=models.PositiveIntegerField(
                default=0, help_text="Posts in last 14 days"
            ),
        ),
        migrations.AddField(
            model_name="socialmediaaccount",
            name="social_blade_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(
                fields=["username"], name="influencers_usernam_eac8e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(
                fields=["country", "is_influencer"],
                name="influencers_country_a5d309_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(
                fields=["primary_category"], name="influencers_primary_dffd1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(
                fields=["is_verified", "is_active"],
                name="influencers_is_veri_04d2c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socialmediaaccount",
            index=models.Index(
                fields=["platform", "followers_count"],
                name="influencers_platfor_2d5a6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socialmediaaccount",
            index=models.Index(
                fields=["influencer", "is_active"],
                name="influencers_influen_e1931d_idx",
            ),
        ),
        migrations.AddField(
            model_name="sponsoredpost",
            name="influencer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_posts",
                to="influencers.influencer",
            ),
        ),
        migrations.AddField(
            model_name="sponsoredpost",
            name="social_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_posts",
                to="influencers.socialmediaaccount",
            ),
        ),
        migrations.AddField(
            model_name="influencerdataimport",
            name="started_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoredpost",
            index=models.Index(
                fields=["brand_name"], name="influencers_brand_n_e258ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoredpost",
            index=models.Index(
                fields=["campaign_type"], name="influencers_campaig_58d41d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoredpost",
            index=models.Index(
                fields=["influencer", "posted_at"],
                name="influencers_influen_afc414_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoredpost",
            index=models.Index(
                fields=["views_count"], name="influencers_views_c_8751e2_idx"
            ),
        ),
    ]
