# Generated by Django 4.2.11 on 2025-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("influencers", "0002_influencerdataimport_sponsoredpost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="influencer",
            name="avg_comments",
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="avg_likes",
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="avg_saves",
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="avg_shares",
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="avg_views",
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="followers_growth_14d",
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="followers_growth_rate_14d",
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="posts_count_14d",
        ),
        migrations.AlterField(
            model_name="influencer",
            name="username",
            field=models.CharField(
                help_text="Primary username (usually Instagram)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
