# Generated by Django 4.2.11 on 2025-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("agency", "Agency"),
                    ("influencer", "Influencer"),
                    ("brand", "Brand"),
                    ("admin", "Admin"),
                ],
                default="agency",
                max_length=20,
            ),
        ),
    ]
