# Generated by Django 4.2.11 on 2025-11-07 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("influencers", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("campaign_performance", "Campaign Performance"),
                            ("influencer_analytics", "Influencer Analytics"),
                            ("audience_insights", "Audience Insights"),
                            ("roi_analysis", "ROI Analysis"),
                            ("competitive_analysis", "Competitive Analysis"),
                            ("trend_analysis", "Trend Analysis"),
                            ("agency_dashboard", "Agency Dashboard"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("default_parameters", models.JSONField(default=dict)),
                ("default_filters", models.JSONField(default=dict)),
                ("chart_configurations", models.JSONField(default=list)),
                (
                    "sections",
                    models.JSONField(
                        default=list, help_text="Report sections and layout"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_agencies",
                    models.ManyToManyField(blank=True, to="agencies.agency"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "db_table": "reports_template",
            },
        ),
        migrations.CreateModel(
            name="ReportSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(help_text="Comma-separated email addresses"),
                ),
                ("slack_webhook_url", models.URLField(blank=True, null=True)),
                ("custom_webhook_url", models.URLField(blank=True, null=True)),
                (
                    "delivery_time",
                    models.TimeField(help_text="Time of day to deliver reports"),
                ),
                (
                    "delivery_day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week for weekly reports (0=Monday)",
                        null=True,
                    ),
                ),
                (
                    "delivery_day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month for monthly reports (1-28)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_delivered", models.DateTimeField(blank=True, null=True)),
                ("next_delivery", models.DateTimeField(blank=True, null=True)),
                ("report_parameters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_subscriptions",
                        to="agencies.agency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Subscription",
                "verbose_name_plural": "Report Subscriptions",
                "db_table": "reports_subscription",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("campaign_performance", "Campaign Performance"),
                            ("influencer_analytics", "Influencer Analytics"),
                            ("audience_insights", "Audience Insights"),
                            ("roi_analysis", "ROI Analysis"),
                            ("competitive_analysis", "Competitive Analysis"),
                            ("trend_analysis", "Trend Analysis"),
                            ("agency_dashboard", "Agency Dashboard"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Report configuration parameters"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict, help_text="Applied filters and date ranges"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("dashboard", "Dashboard View"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                (
                    "report_data",
                    models.JSONField(default=dict, help_text="Structured report data"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("generation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("next_generation_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="agencies.agency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Dashboard"),
                            ("campaign_manager", "Campaign Manager"),
                            ("influencer_manager", "Influencer Manager"),
                            ("financial", "Financial Dashboard"),
                            ("custom", "Custom Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict, help_text="Dashboard layout configuration"
                    ),
                ),
                (
                    "widgets",
                    models.JSONField(default=list, help_text="Widget configurations"),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "auto_refresh_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Auto-refresh interval in seconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="agencies.agency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "db_table": "reports_dashboard",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("campaign", "Campaign Metrics"),
                            ("influencer", "Influencer Metrics"),
                            ("agency", "Agency Metrics"),
                            ("platform", "Platform Metrics"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of metrics at this point in time",
                    ),
                ),
                ("snapshot_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="agencies.agency",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="influencers.influencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Snapshot",
                "verbose_name_plural": "Analytics Snapshots",
                "db_table": "reports_snapshot",
                "ordering": ["-snapshot_date"],
            },
        ),
    ]
