# Generated by Django 4.2.11 on 2025-11-07 16:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Agency Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="agency_logos/"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(default="Morocco", max_length=100)),
                (
                    "agency_size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1-10 employees)"),
                            ("medium", "Medium (11-50 employees)"),
                            ("large", "Large (51+ employees)"),
                        ],
                        default="small",
                        max_length=20,
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "specialties",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of specialties (e.g., Fashion, Tech, Food)",
                        null=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_documents",
                    models.FileField(
                        blank=True,
                        help_text="Upload business registration or other verification documents",
                        null=True,
                        upload_to="verification_docs/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
                "db_table": "agencies_agency",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgencySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("trial", "Trial"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("max_campaigns", models.PositiveIntegerField(default=5)),
                ("max_influencer_searches", models.PositiveIntegerField(default=100)),
                ("max_team_members", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="agencies.agency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "agencies_subscription",
            },
        ),
        migrations.CreateModel(
            name="AgencyTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("account_manager", "Account Manager"),
                            ("strategist", "Strategist"),
                            ("creative", "Creative"),
                            ("analyst", "Analyst"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="agencies.agency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "db_table": "agencies_teammember",
                "unique_together": {("agency", "user")},
            },
        ),
    ]
