# Generated by Django 4.2.11 on 2025-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0002_teaminvitation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={
                "ordering": ["name"],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.RenameField(
            model_name="teaminvitation",
            old_name="created_at",
            new_name="sent_at",
        ),
        migrations.AlterUniqueTogether(
            name="teaminvitation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="agency",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="agency_size",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="verification_documents",
        ),
        migrations.RemoveField(
            model_name="agencysubscription",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="agencysubscription",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="agency",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="average_campaign_roi",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="agency",
            name="brand_colors",
            field=models.CharField(
                blank=True, help_text="Primary brand colors (hex codes)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="Public display name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Technology"),
                    ("software", "Software & SaaS"),
                    ("fintech", "Fintech"),
                    ("ecommerce", "E-commerce"),
                    ("gaming", "Gaming"),
                    ("fashion", "Fashion & Apparel"),
                    ("beauty", "Beauty & Cosmetics"),
                    ("food_beverage", "Food & Beverage"),
                    ("health_wellness", "Health & Wellness"),
                    ("fitness", "Fitness & Sports"),
                    ("home_lifestyle", "Home & Lifestyle"),
                    ("luxury", "Luxury Goods"),
                    ("marketing", "Marketing & Advertising"),
                    ("consulting", "Consulting"),
                    ("finance", "Financial Services"),
                    ("real_estate", "Real Estate"),
                    ("education", "Education"),
                    ("healthcare", "Healthcare"),
                    ("travel", "Travel & Tourism"),
                    ("automotive", "Automotive"),
                    ("entertainment", "Entertainment & Media"),
                    ("nonprofit", "Non-Profit"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                help_text="Primary industry or focus area",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agency",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="monthly_budget_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_1k", "Under $1,000/month"),
                    ("1k_5k", "$1,000 - $5,000/month"),
                    ("5k_15k", "$5,000 - $15,000/month"),
                    ("15k_50k", "$15,000 - $50,000/month"),
                    ("50k_100k", "$50,000 - $100,000/month"),
                    ("over_100k", "Over $100,000/month"),
                ],
                help_text="Typical monthly influencer marketing budget",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="organization_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("startup", "Startup (1-10 employees)"),
                    ("small", "Small (11-50 employees)"),
                    ("medium", "Medium (51-200 employees)"),
                    ("large", "Large (201-1000 employees)"),
                    ("enterprise", "Enterprise (1000+ employees)"),
                ],
                help_text="Number of employees",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("agency", "Marketing Agency"),
                    ("brand", "Brand/Company"),
                    ("freelancer", "Freelance Marketer"),
                ],
                default="agency",
                help_text="Type of organization",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="target_demographics",
            field=models.TextField(
                blank=True, help_text="Target audience demographics"
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="total_campaigns_run",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agency",
            name="total_influencers_worked_with",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agency",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="agencysubscription",
            name="currency",
            field=models.CharField(default="MAD", max_length=3),
        ),
        migrations.AddField(
            model_name="agencysubscription",
            name="max_reports_per_month",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="agencysubscription",
            name="monthly_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="agencyteammember",
            name="can_invite_members",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agencyteammember",
            name="can_manage_billing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agencyteammember",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="agencyteammember",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("full_access", "Full Access"),
                    ("campaign_management", "Campaign Management"),
                    ("influencer_management", "Influencer Management"),
                    ("analytics_only", "Analytics Only"),
                    ("content_review", "Content Review Only"),
                    ("read_only", "Read Only"),
                ],
                default="read_only",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("full_access", "Full Access"),
                    ("campaign_management", "Campaign Management"),
                    ("influencer_management", "Influencer Management"),
                    ("analytics_only", "Analytics Only"),
                    ("content_review", "Content Review Only"),
                    ("read_only", "Read Only"),
                ],
                default="read_only",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="response_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Brief description of your organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agency",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="agency",
            name="founded_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Verified organization"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="agencies/logos/"),
        ),
        migrations.AlterField(
            model_name="agency",
            name="name",
            field=models.CharField(help_text="Organization name", max_length=200),
        ),
        migrations.AlterField(
            model_name="agency",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agency",
            name="specialties",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated list of specialties (agencies) or product categories (brands)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agency",
            name="website",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agencysubscription",
            name="max_campaigns",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="agencysubscription",
            name="max_influencer_searches",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="agencysubscription",
            name="max_team_members",
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AlterField(
            model_name="agencysubscription",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Plan"),
                    ("pro", "Pro Plan"),
                    ("enterprise", "Enterprise Plan"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agencysubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "Free Trial"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agencyteammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Campaign Manager"),
                    ("account_manager", "Account Manager"),
                    ("strategist", "Strategist"),
                    ("creative", "Creative Director"),
                    ("analyst", "Data Analyst"),
                    ("coordinator", "Coordinator"),
                    ("intern", "Intern"),
                ],
                default="coordinator",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="teaminvitation",
            name="message",
            field=models.TextField(
                blank=True, default="", help_text="Personal message to include"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teaminvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Campaign Manager"),
                    ("account_manager", "Account Manager"),
                    ("strategist", "Strategist"),
                    ("creative", "Creative Director"),
                    ("analyst", "Data Analyst"),
                    ("coordinator", "Coordinator"),
                    ("intern", "Intern"),
                ],
                default="coordinator",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="teaminvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teaminvitation",
            unique_together={("agency", "email", "status")},
        ),
        migrations.AlterModelTable(
            name="agencyteammember",
            table="agencies_team_member",
        ),
        migrations.AlterModelTable(
            name="teaminvitation",
            table="agencies_team_invitation",
        ),
    ]
