# Generated by Django 4.2.11 on 2025-11-07 18:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("influencers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("brand_awareness", "Brand Awareness"),
                            ("product_launch", "Product Launch"),
                            ("engagement", "Engagement"),
                            ("conversions", "Conversions"),
                            ("event_promotion", "Event Promotion"),
                            ("user_generated_content", "User Generated Content"),
                        ],
                        max_length=50,
                    ),
                ),
                ("brand_name", models.CharField(max_length=200)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "target_audience",
                    models.TextField(help_text="Describe your target audience"),
                ),
                (
                    "campaign_objectives",
                    models.TextField(help_text="What are you trying to achieve?"),
                ),
                ("total_budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("budget_currency", models.CharField(default="MAD", max_length=3)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("content_guidelines", models.TextField(blank=True, null=True)),
                (
                    "hashtags",
                    models.CharField(
                        blank=True,
                        help_text="Required hashtags",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "mentions",
                    models.CharField(
                        blank=True,
                        help_text="Required mentions",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "brief_document",
                    models.FileField(
                        blank=True, null=True, upload_to="campaign_briefs/"
                    ),
                ),
                (
                    "brand_assets",
                    models.FileField(blank=True, null=True, upload_to="brand_assets/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="agencies.agency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "campaigns_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InfluencerCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "Social Media Post"),
                            ("story", "Story"),
                            ("reel", "Reel/Video"),
                            ("igtv", "IGTV"),
                            ("youtube_video", "YouTube Video"),
                            ("tiktok_video", "TikTok Video"),
                            ("live_stream", "Live Stream"),
                            ("multiple", "Multiple Content Types"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "deliverables_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of posts/videos required"
                    ),
                ),
                ("agreed_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="MAD", max_length=3)),
                ("deadline", models.DateField()),
                ("specific_requirements", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("in_progress", "In Progress"),
                            ("content_submitted", "Content Submitted"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("actual_reach", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "actual_engagement",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="influencers.influencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Influencer Collaboration",
                "verbose_name_plural": "Influencer Collaborations",
                "db_table": "campaigns_collaboration",
                "unique_together": {("campaign", "influencer")},
            },
        ),
        migrations.CreateModel(
            name="CampaignContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaign_content/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="campaign_content/videos/"
                    ),
                ),
                (
                    "post_url",
                    models.URLField(
                        blank=True, help_text="URL of the published content", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("revision_requested", "Revision Requested"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback from agency", null=True
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="campaigns.influencercollaboration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Content",
                "verbose_name_plural": "Campaign Content",
                "db_table": "campaigns_content",
            },
        ),
        migrations.CreateModel(
            name="CampaignAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_reach", models.PositiveIntegerField(default=0)),
                ("total_impressions", models.PositiveIntegerField(default=0)),
                ("total_likes", models.PositiveIntegerField(default=0)),
                ("total_comments", models.PositiveIntegerField(default=0)),
                ("total_shares", models.PositiveIntegerField(default=0)),
                ("total_saves", models.PositiveIntegerField(default=0)),
                ("avg_engagement_rate", models.FloatField(default=0.0)),
                (
                    "cost_per_engagement",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("website_clicks", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("conversion_rate", models.FloatField(default=0.0)),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("roi_percentage", models.FloatField(default=0.0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Analytics",
                "verbose_name_plural": "Campaign Analytics",
                "db_table": "campaigns_analytics",
            },
        ),
    ]
